/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItemInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const MenuItem = IDL.Record({
  'itemId' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Variant({ 'notFound' : IDL.Null }),
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'out_for_delivery' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const CustomerOrder = IDL.Record({
  'status' : OrderStatus,
  'orderId' : IDL.Text,
  'timestamp' : IDL.Int,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Float64,
});
export const CustomerProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderInput = IDL.Record({
  'orderId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const ProfileInput = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const MenuItemUpdate = IDL.Record({
  'itemId' : IDL.Text,
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func([MenuItemInput], [MenuItem], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [Result], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [CustomerOrder], ['query']),
  'getOrdersByCustomerId' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CustomerOrder)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([OrderInput], [], []),
  'saveCallerUserProfile' : IDL.Func([ProfileInput], [], []),
  'toggleMenuItemAvailability' : IDL.Func([IDL.Text], [MenuItem], []),
  'updateMenuItem' : IDL.Func([MenuItemUpdate], [MenuItem], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItemInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const MenuItem = IDL.Record({
    'itemId' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({
    'ok' : IDL.Null,
    'err' : IDL.Variant({ 'notFound' : IDL.Null }),
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'out_for_delivery' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const CustomerOrder = IDL.Record({
    'status' : OrderStatus,
    'orderId' : IDL.Text,
    'timestamp' : IDL.Int,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Float64,
  });
  const CustomerProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const OrderInput = IDL.Record({
    'orderId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const ProfileInput = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const MenuItemUpdate = IDL.Record({
    'itemId' : IDL.Text,
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func([MenuItemInput], [MenuItem], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [Result], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
    'getOrderById' : IDL.Func([IDL.Text], [CustomerOrder], ['query']),
    'getOrdersByCustomerId' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CustomerOrder)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([OrderInput], [], []),
    'saveCallerUserProfile' : IDL.Func([ProfileInput], [], []),
    'toggleMenuItemAvailability' : IDL.Func([IDL.Text], [MenuItem], []),
    'updateMenuItem' : IDL.Func([MenuItemUpdate], [MenuItem], []),
  });
};

export const init = ({ IDL }) => { return []; };