/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerOrder {
  'status' : OrderStatus,
  'orderId' : string,
  'timestamp' : bigint,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
}
export interface CustomerProfile { 'name' : string, 'phone' : string }
export interface MenuItem {
  'itemId' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : number,
}
export interface MenuItemInput {
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : number,
}
export interface MenuItemUpdate {
  'itemId' : string,
  'name' : [] | [string],
  'description' : [] | [string],
  'category' : [] | [string],
  'price' : [] | [number],
}
export interface OrderInput { 'orderId' : string, 'items' : Array<OrderItem> }
export interface OrderItem {
  'itemName' : string,
  'quantity' : bigint,
  'price' : number,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'out_for_delivery' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface ProfileInput { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[MenuItemInput], MenuItem>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<CustomerOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getMenuByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getOrderById' : ActorMethod<[string], CustomerOrder>,
  'getOrdersByCustomer' : ActorMethod<[Principal], Array<CustomerOrder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [CustomerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[OrderInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[ProfileInput], undefined>,
  'toggleMenuItemAvailability' : ActorMethod<[string], MenuItem>,
  'updateMenuItem' : ActorMethod<[MenuItemUpdate], MenuItem>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];